# Note: ACTIONS_RESULTS_URL must end in a trailing "/"
# It's unclear if we need to set both CUSTOM_ACTIONS_RESULTS_URL and ACTIONS_RESULTS_URL
# See: https://gha-cache-server.falcondev.io/getting-started

githubConfigUrl: "https://github.com/pyvista"
template:
  spec:
    securityContext:
      runAsUser: 1001
      runAsGroup: 1001
      fsGroup: 1001
    containers:
      - name: runner
        image: ghcr.io/pyvista/arc-runners:ubuntu22.04-latest
        imagePullPolicy: Always
        command: ["/home/runner/run.sh"]
        env:
          - name: RUNNER_TOOL_CACHE
            value: /opt/hostedtoolcache
          - name: AGENT_TOOLSDIRECTORY
            value: /opt/hostedtoolcache
          - name: ACTIONS_RESULTS_URL
            value: "http://gha-actions-cache-gha-actions-cache-server.actions-cache.svc.cluster.local/"
          - name: CUSTOM_ACTIONS_RESULTS_URL
            value: "http://gha-actions-cache-gha-actions-cache-server.actions-cache.svc.cluster.local/"
          - name: PIP_TRUSTED_HOST
            value: "devpi.devpi.svc.cluster.local"
          - name: PIP_INDEX_URL
            value: "http://devpi.devpi.svc.cluster.local/root/pypi"
          - name: UV_INDEX
            value: "http://devpi.devpi.svc.cluster.local/root/pypi"
        volumeMounts:
          - name: toolcache
            mountPath: /opt/hostedtoolcache
        resources:
          requests:
            cpu: "2"
            memory: "2Gi"
          limits:
            cpu: "8"
            memory: "32Gi"
    volumes:
      - name: toolcache
        hostPath:
          path: /var/lib/runner-toolcache-22.04
          type: DirectoryOrCreate
