name: Test ARC
on: [push]

jobs:
  test:
    runs-on: "ubuntu-22.04-self-hosted"
    steps:
      - name: Show System Info
        run: |
          sudo apt update
          sudo apt install -y neofetch
          neofetch
